-- Final migration: ensure all current question types are allowed
-- Run this ONCE in the Supabase SQL Editor (Dashboard → SQL Editor → New query).
-- Safe to re-run — drops and recreates constraints idempotently.
--
-- This revision adds 'active_dx' (new "אבחנות פעילות" rubric) and 'radio_challenge'
-- (already generated by the Edge Function, but missing from this constraint until now).

-- ── daily_questions ──────────────────────────────────────────────────────────

ALTER TABLE daily_questions
  DROP CONSTRAINT IF EXISTS daily_questions_question_type_check;

ALTER TABLE daily_questions
  ADD CONSTRAINT daily_questions_question_type_check
  CHECK (question_type IN (
    'bls', 'als',
    'med_v3', 'med_v4',
    'abbr', 'improvised',
    'red_flag', 'spot_error', 'med_bag',
    'radio_challenge', 'active_dx'
  ));

-- ── daily_responses ───────────────────────────────────────────────────────────

ALTER TABLE daily_responses
  DROP CONSTRAINT IF EXISTS daily_responses_question_type_check;

ALTER TABLE daily_responses
  ADD CONSTRAINT daily_responses_question_type_check
  CHECK (question_type IN (
    'bls', 'als',
    'med_v3', 'med_v4',
    'abbr', 'improvised',
    'red_flag', 'spot_error', 'med_bag',
    'radio_challenge', 'active_dx'
  ));

-- ── Verify ────────────────────────────────────────────────────────────────────

SELECT conname, pg_get_constraintdef(oid)
FROM   pg_constraint
WHERE  conrelid IN ('daily_questions'::regclass, 'daily_responses'::regclass)
AND    contype = 'c'
ORDER  BY conrelid::text, conname;
